// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rysxmhjqfinbsuuafgbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5c3htaGpxZmluYnN1dWFmZ2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjY1NzgsImV4cCI6MjA2ODkwMjU3OH0.bP-Juzyn-Df8MO4LtK6jKv2B5wAMj_vfUVZtpcK3nOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});